name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  default_ci:
    name: Run default CI of repository
    uses: ./.github/workflows/ci.yml

  npm:
    name: Publish library to NPM
    needs: default_ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: ./.github/actions/pnpm
      - name: Build
        run: pnpm build
      - name: Publish
        run: pnpm publish --provenance --access public --no-git-checks
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  jsr:
    name: Publish library to JSR
    needs: default_ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish
        run: npx jsr publish
